version: '3.9'

services:

  api:
    container_name: auth
    image: auth
    ports:
      - "5055:5054"                 
    networks:
      - mynetwork

  angular:
    container_name: angular
    image: angular
    ports:
      - "8080:80"                   
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
